Input Component
code0-tech/base-ui pull request #5
Opened 2023-12-07 11:07 UTC by nicosammito

2023-12-07 19:46 UTC, Taucher2003 requested changes
I also see some files are missing a final newline, please fix this 🙂

2023-12-07 19:46 UTC, Taucher2003 commented on .storybook/theme.js
> +    brandImage: 'https://cdn.discordapp.com/attachments/1173726744130375791/1176472242469740604/Logo.png',
This will break in a short amount of time because Discord is implementing expiring links for attachments.

2023-12-07 19:46 UTC, Taucher2003 commented on package.json
> +  "version": "0.1.0-pre-alpha",
We set the version during publishing in the pipeline, should we keep this one as 0.0.0 then because it will never be automatically updated?

2023-12-07 19:46 UTC, Taucher2003 commented on src/components/input/Input.stories.tsx
> +export const Mail = () => <Input>
Is it intended that some of the variants don't have an icon set? They look a bit odd in the storybook

2023-12-07 19:46 UTC, Taucher2003 commented on src/components/input/Input.style.scss
> +      content: url('data:image/svg+xml; utf8, <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMin slice" width="12" height="12" viewBox="0 -2 24 24" stroke-width="2" stroke="rgba(25
Should we have a comment here explaining what type of icon this is?

2023-12-07 19:46 UTC, Taucher2003 commented on src/components/input/Input.style.scss
> +        content: url('data:image/svg+xml; utf8, <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMin slice" width="12" height="12" viewBox="0 -2 24 24" stroke-width="2" stroke="rgba(
Should we have a comment here explaining what type of icon this is?

2023-12-09 15:09 UTC, nicosammito commented on .storybook/theme.js
> +    brandImage: 'https://cdn.discordapp.com/attachments/1173726744130375791/1176472242469740604/Logo.png',
for the moment its okay. But we will change this in the future

2023-12-09 15:10 UTC, nicosammito commented on src/components/input/Input.stories.tsx
> +export const Mail = () => <Input>
yes its intended to check the availability if no Icon is provided

2023-12-09 15:11 UTC, nicosammito commented on package.json
> +  "version": "0.1.0-pre-alpha",
No we should implement an auto updater for the package file as well. But we do not track it over the package file

2023-12-09 15:12 UTC, nicosammito commented on src/components/input/Input.style.scss
> +      content: url('data:image/svg+xml; utf8, <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMin slice" width="12" height="12" viewBox="0 -2 24 24" stroke-width="2" stroke="rgba(25
Good idea 👍🏻

2023-12-09 15:12 UTC, nicosammito commented on src/components/input/Input.style.scss
> +        content: url('data:image/svg+xml; utf8, <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMin slice" width="12" height="12" viewBox="0 -2 24 24" stroke-width="2" stroke="rgba(
as commented above

2023-12-09 15:26 UTC, Taucher2003 approved these changes
Without specific react knowledge and without being a css expert, this looks ok to me

2023-12-09 15:26 UTC, merged